/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
export { MyToken__factory } from "./MyToken__factory";
