/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenizedBallotSol from "./TokenizedBallot.sol";
export type { tokenizedBallotSol };
export type { MyToken } from "./MyToken";
